#Makefile generated by NAG Fortran Builder
#The following macros are machine specific
fblib = ../nagf7/lib
NI_NAGFOR_Compiler = nagfor
NI_NAGFOR_CompOpts = -ideclient -abi=64 -g -C
NI_NAGFOR_NAGFORInfo = -gfb
NI_NAGFOR_CompOnly = -c
NI_NAGFOR_IFLAGS = 
NI_C_Compiler = nagfor =C
NI_C_CompOpts = -ideclient -abi=64 -g -Wc,-Wall
NI_C_CompOnly = -c
NI_IFLAGS = -I../nagf7/bin/resource/NL284/nag_interface_blocks_nagfor -I../naglib27/bin 
NI_CPP_Compiler = nagfor
NI_ALLOPTS = 
NI_Link = nagfor
NI_LibPath = -L../nagf7/lib64 -L$(fblib) 
NI_LDFLAGS = 
NI_RM = fbrm 

#File extensions used in this Makefile
.SUFFIXES:
.SUFFIXES: .f90 .o 

#Output file
NI_OUTPUT = trapezium_area.exe

#Target name
NI_TARGET = trapezium_area.exe

#Object files
NI_OBJS =	 \
	trapezium_area.o

#Depend Object files
NI_DOBJS =	 \
	trapezium_area.o

#Prospective Module files
NI_MODS =	
#Fortran Information files
NI_FIFS =	 \
	trapezium_area.fif

#Library files
NI_LIBS = C:\naglib27\bin\NLW6I284E_mkl.dll 

#Dependencies
NI_EQ==
NI_SC=\;
trapezium_area.o:	trapezium_area.f90

#Default make target rule
$(NI_TARGET):$(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) @'trapezium_area.mako' $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Other rules
trapezium_area.o:
	@echo @nagfor trapezium_area.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) trapezium_area.fif -c trapezium_area.f90

#Rebuild rule
all:clean $(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) @'trapezium_area.mako' $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Clean rule
clean:
	$(NI_RM) $(NI_OUTPUT)
	$(NI_RM) trapezium_area.o
	$(NI_RM) $(NI_MODS)
	$(NI_RM) trapezium_area.fif
	$(NI_RM) fbvalwatch.vwi

#Clean all rule
clean_all:
	$(NI_RM) '*.exe' '*.a' '*.dll' '*.o' '*.mod' '*.fif' '*.bak' fbvalwatch.vwi
